In [2]:
import torch

# Создание тензоров
tensor_a = torch.tensor([[1.0, 2.0], 
                         [3.0, 4.0]])

tensor_b = torch.tensor([[5.0, 6.0], 
                         [7.0, 8.0]])

# Сложение тензоров
tensor_sum = tensor_a + tensor_b
print("Сумма тензоров:\n", tensor_sum)

# Транспонирование тензора
tensor_transpose = tensor_a.T
print("Транспонирование тензора:\n", tensor_transpose)

# Матричное умножение тензоров
tensor_matmul = torch.matmul(tensor_a, tensor_b)
print("Матричное умножение тензоров:\n", tensor_matmul)

Сумма тензоров:
 tensor([[ 6.,  8.],
        [10., 12.]])
Транспонирование тензора:
 tensor([[1., 3.],
        [2., 4.]])
Матричное умножение тензоров:
 tensor([[19., 22.],
        [43., 50.]])


In [3]:
import torch

# Создаем тензор с возможностью вычисления градиента
x = torch.tensor(2.0, requires_grad=True)

# Вычисляем функцию от x
y = x ** 2

# Вычисляем градиент y по отношению к x
y.backward()

# Вывод градиента
print("Градиент y по отношению к x:", x.grad)

Градиент y по отношению к x: tensor(4.)


In [4]:
import torch
import torch.nn as nn

# Определение простой CNN для классификации изображений
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(16 * 16 * 16, 10)  # CIFAR-10, 10 классов

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = x.view(-1, 16 * 16 * 16)  # Приведение к вектору
        x = self.fc1(x)  # Полносвязный слой
        return x

In [5]:
import torch.nn as nn

# Создание сверточного слоя с 32 фильтрами и ядром 3x3
conv_layer = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, padding=1)

In [6]:
import torch.nn as nn

# Применение Max Pooling с размером окна 2x2
maxpool = nn.MaxPool2d(kernel_size=2, stride=2)

# Применение Average Pooling с размером окна 2x2
avgpool = nn.AvgPool2d(kernel_size=2, stride=2)

In [7]:
import torch.nn as nn

# Инициализация различных активационных функций
relu = nn.ReLU()
sigmoid = nn.Sigmoid()
tanh = nn.Tanh()

# Применение активационной функции
x = torch.tensor([-1.0, 0.0, 1.0])  # Пример входных данных
print("ReLU:", relu(x))
print("Sigmoid:", sigmoid(x))
print("Tanh:", tanh(x))

ReLU: tensor([0., 0., 1.])
Sigmoid: tensor([0.2689, 0.5000, 0.7311])
Tanh: tensor([-0.7616,  0.0000,  0.7616])


In [8]:
from torchvision import transforms

# Определение пайплайна для аугментации изображений
transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),   # Случайное горизонтальное отражение
    transforms.RandomRotation(10),       # Случайное вращение на 10 градусов
    transforms.ToTensor()                # Конвертация в тензор
])

ModuleNotFoundError: No module named 'torchvision'

In [9]:
%pip install torchvision

In [ ]:
import torch.optim as optim

# Использование оптимизатора Adam с начальным learning rate
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Пример изменения batch size для DataLoader
from torch.utils.data import DataLoader
train_loader = DataLoader(dataset, batch_size=64, shuffle=True)

# Изменение гиперпараметров в зависимости от этапа обучения
optimizer.param_groups[0]['lr'] = 0.0005  # Снижение learning rate в процессе обучения


In [ ]:
import torch.nn as nn

# Создание слоя Batch Normalization для сверточного слоя
bn = nn.BatchNorm2d(16)  # Для слоя с 16 каналами

# Пример использования Batch Normalization в слое CNN
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(16)

    def forward(self, x):
        x = torch.relu(self.bn1(self.conv1(x)))  # Применение Batch Norm после свертки
        return x


In [ ]:
import torch.nn as nn

# Пример использования Dropout с вероятностью 0.5
dropout = nn.Dropout(p=0.5)

# Встроим Dropout в полносвязную нейронную сеть
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(128, 64)
        self.dropout = nn.Dropout(p=0.5)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.dropout(x)  # Применение Dropout
        return x


In [ ]:
import torch.optim as optim

# Пример использования learning rate в оптимизаторе SGD
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Применение scheduler для динамического изменения learning rate
from torch.optim.lr_scheduler import StepLR
scheduler = StepLR(optimizer, step_size=5, gamma=0.1)  # Понижение lr на каждом 5 шаге


In [ ]:
from torch.optim import SGD
from torch.optim.lr_scheduler import CyclicLR

# Оптимизатор с базовым learning rate
optimizer = SGD(model.parameters(), lr=0.01)

# CyclicLR scheduler с минимальным и максимальным lr
scheduler = CyclicLR(optimizer, base_lr=0.001, max_lr=0.01, step_size_up=5, mode='triangular')


In [ ]:
import torch.optim as optim

# Использование Adam с адаптивным learning rate
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Пример обновления learning rate вручную
for epoch in range(epochs):
    if epoch % 10 == 0:
        for param_group in optimizer.param_groups:
            param_group['lr'] *= 0.9  # Понижение lr каждые 10 эпох


In [ ]:
from torch.utils.data import DataLoader

# Установка batch size при загрузке данных
train_loader = DataLoader(dataset, batch_size=32, shuffle=True)

# Обход по данным с использованием batch size
for images, labels in train_loader:
    # Процесс обучения модели
    pass


In [ ]:
import torch

correct = 0
total = 0

# Оценка точности на тестовом наборе данных
with torch.no_grad():
    for data in test_loader:
        images, labels = data
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy: {100 * correct / total}%')


In [ ]:
from sklearn.metrics import precision_score

# Пример истинных и предсказанных значений
y_true = [0, 1, 1, 0, 1, 1]
y_pred = [0, 1, 0, 0, 1, 1]

# Расчет Precision
precision = precision_score(y_true, y_pred)
print("Precision:", precision)


In [ ]:
from sklearn.metrics import recall_score

# Пример истинных и предсказанных значений
y_true = [0, 1, 1, 0, 1, 1]
y_pred = [0, 1, 0, 0, 1, 1]

# Расчет Recall
recall = recall_score(y_true, y_pred)
print("Recall:", recall)


In [ ]:
from sklearn.metrics import f1_score

# Пример истинных и предсказанных значений
y_true = [0, 1, 1, 0, 1, 1]
y_pred = [0, 1, 0, 0, 1, 1]

# Расчет F1-score
f1 = f1_score(y_true, y_pred)
print("F1 Score:", f1)


In [ ]:
from sklearn.metrics import roc_auc_score

# Пример истинных меток и предсказанных вероятностей
y_true = [0, 1, 1, 0, 1, 1]
y_pred_prob = [0.1, 0.9, 0.8, 0.3, 0.6, 0.75]

# Расчет ROC-AUC
roc_auc = roc_auc_score(y_true, y_pred_prob)
print("ROC-AUC:", roc_auc)
